### ISSUE TITLE
need a demo app

### ISSUE THREAD

**Issue by joeaudette** [jasongaylord/gaylordsolutions.TwitterWidget#1]
Hi Jason,

This repo needs a demo app, I'd be happy to fork it and make a pull request unless you are already working on it.
Also in the readme it says:

>.AddApplicationPart(typeof(cloudscribe.TwitterWidget.Controllers.TwitterWidgetController).GetTypeInfo().Assembly)

that should not be needed. It should work with a project reference or a nuget reference without that.

I saw you tweeted about it and I'm planning to retweet once I'm sure there is a working example, as I gathered from https://github.com/cloudscribe/cloudscribe.SimpleContent/issues/351 that it isn't working. Happy to help solve that but I'm sure it is not an issue caused by cloudscribe.

**Comment by jasongaylord** [comment]
@joeaudette I've published the sample app. You'll need to plug in a TwitterSecret and a TwitterConsumerKey. Those are private to you. However, if I do that in the sample app, it works fine. Where it doesn't seem to be working in CloudScribe is when I'm adding this to a custom theme.

Good catch on the readme. It was originally needed when referencing just the DLL. I've since updated the readme.

**Comment by joeaudette** [comment]
@jasongaylord I'll give it a try later today. You're just invoking it from the _layout file in a cloudscribe theme and it fails to find the view?
